name: Continuous Delivery
on:
  push:
    branches:
      - main # ou qq outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Simulando Continuous Delivery
        uses: actions/upload-pages-artifact@v4
        with:
          name: projetozipado.zip
          path: '.'

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado2.zip
      - name: Display structure of downloaded files
        run: ls -R